root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build-dynamic"
  bin = "./bin/sqlite-server.bin"
  full_bin = "./bin/sqlite-server.bin"
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "sql", "json", "sh"]
  include_dir = ["cmd", "internal"]
  exclude_file = []
  delay = 1000 # ms
  stop_on_error = true
  log = "air_errors.log"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
